# Generated by Django 3.1.2 on 2020-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('cantidad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=30)),
            ],
        ),
    ]
